executable = /lustre/home/tgebhard/tf-1.0.0_gpu/bin/python3

getenv = True

request_memory = 16384
request_cpus = 4
request_gpus = 2

# Do not start jobs on "Black Hole Machines"
requirements = ((Target.Machine =!= "g008.internal.cluster.is.localnet") && (Target.Machine =!= "g009.internal.cluster.is.localnet") && (Target.Machine =!= "g010.internal.cluster.is.localnet"))


output = cluster_logs/reg_param_GW170104_0100_0300_1e-06.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_1e-06.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_1e-06.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 1e-06, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=1e-06"
queue

output = cluster_logs/reg_param_GW170104_0100_0300_5e-06.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_5e-06.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_5e-06.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 5e-06, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=5e-06"
queue

output = cluster_logs/reg_param_GW170104_0100_0300_1e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_1e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_1e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 1e-05, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=1e-05"
queue

output = cluster_logs/reg_param_GW170104_0100_0300_2e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_2e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_2e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 2e-05, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=2e-05"
queue

output = cluster_logs/reg_param_GW170104_0100_0300_5e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_5e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_5e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 5e-05, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=5e-05"
queue

output = cluster_logs/reg_param_GW170104_0100_0300_0.0001.out.$(Process)
error = cluster_logs/reg_param_GW170104_0100_0300_0.0001.err.$(Process)
log = cluster_logs/reg_param_GW170104_0100_0300_0.0001.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 0.0001, [GW170104, 0100_0300]' --distances=0100_0300 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=0.0001"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_1e-06.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_1e-06.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_1e-06.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 1e-06, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=1e-06"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_5e-06.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_5e-06.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_5e-06.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 5e-06, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=5e-06"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_1e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_1e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_1e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 1e-05, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=1e-05"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_2e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_2e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_2e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 2e-05, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=2e-05"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_5e-05.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_5e-05.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_5e-05.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 5e-05, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=5e-05"
queue

output = cluster_logs/reg_param_GW170104_0400_0800_0.0001.out.$(Process)
error = cluster_logs/reg_param_GW170104_0400_0800_0.0001.err.$(Process)
log = cluster_logs/reg_param_GW170104_0400_0800_0.0001.log.$(Process)
arguments="pytorch_train_timeseries.py --batch-size=16 --description='Regularization Parameter Test: 0.0001, [GW170104, 0400_0800]' --distances=0400_0800 --initial-lr=0.0001 --initial-threshold=0.0 --n-epochs=50 --noise-source=GW170104 --regularization-parameter=0.0001"
queue

